import React from 'react'
import axios from 'axios'
import Head from 'next/head'

const styles = {
    main: {
        padding: 20,
        margin: 20,
        borderBottom: '1px solid #000'
    },
    img: {
        height: 200,
        width: 300
    }
};

export default function PostId({data}) {

    return (
        <>
        {data && (
            <>
                <Head>
                    <title>{data.title}</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                 </Head>
                <div style={styles.main}>
                    <h1>{data.title}</h1>
                    <div>
                        <img src={data.pictures[0]} alt={`ìllustarion de l\'article ${data.title}`} style={styles.img}/>
                    </div>
                    <p>{data.description}</p>
                </div>
            </>
        )}
        </>
    )
}
export const getStaticPaths = async () => {
    const url = 'https://aqueous-meadow-07678.herokuapp.com/api/posts';
    const {data} = await axios.get(url);
    const posts = data.data;
    const paths = posts.map(post => ({
        params: {id: post._id}
    }))
    return {paths, fallback: true};
}
export const getStaticProps = async ({params}) => {
    const id = params.id;
    const url = 'https://aqueous-meadow-07678.herokuapp.com/api/post';
    //On récupère les datas du post
    const {data} = await axios.get(`${url}/${id}`)
    return {
        props: {
            data
        }
    }
}
