import {useEffect} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
/*dynamic -> voir leçon sur "45. Gestion de l'erreur window is not
defined" */
import dynamic from 'next/dynamic'

const Exemple = dynamic(() => import ('../components/localstorage/Exemple'), {ssr: false});
// "ssr: false" signifie qu'on utilise le component "Exemple" que coté client

export default function Home() {

  /*1er solution pour utliser l'objet window coté clien, et notament "localStorage" avec useEffect*/
  useEffect(() => {
    //localStorage.clear();
    //localStorage.setItem('jwt-token', 'azertyuiop87654321')
  }, []);

   /*2eme solution pour utliser l'objet window coté clien, et notament "localStorage" */

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Exemple />
        <h1 className={styles.title}>Bonjour</h1> 
      </main>
    </div>
  )
}
