//getServerSideProps Récupération des données côté serveur
import React from 'react'
import axios from 'axios'
import Link from 'next/link'
import Head from 'next/head'

const style = {
    padding: 10,
    margin: 10,
    borderBottom: '1px solid #000'
};

export default function ApiRegions({data}) {

    return (
        <>
            <Head>
                <title>Liste des regions</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <h1>Cette page utilse getServerSideProps: Rendu coté serveur</h1>
                {data.map(region => (
                    <div key={region.code} style={style}>
                        <Link href="/region/[code]" as={`/region/${region.code}`}>
                            <a><h1>{region.nom}</h1></a>
                        </Link>
                        <p>{region.code}</p>
                    </div>
                ))}
            </div>
        </>
    )
}

export async function getServerSideProps(context) {
    const url = 'https://geo.api.gouv.fr/regions';
    const {data} = await axios.get(url)
    /*Ici on affiche la variable contenu dans le fichier .env*/
    console.log("API_ROOT", process.env.API_ROOT);
    return {
        props: {
            data
        }
    }
    
} 

